services:
  - type: web
    name: hono-api
    runtime: bun
    rootDir: apps/hono-api
    buildCommand: cd ../.. && bun install && cd apps/hono-api && bun run build && ls -la dist
    startCommand: bun run start
    envVars:
      - key: NODE_ENV
        value: production

